api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "credit-limit-payment-rule"
type = "function"
uid = "2e8d5887-941c-994e-51aa-471bb926d79b5d5b1f12"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.payment-methods.transform.run"
  input_query = "src/cart_payment_methods_transform_run.graphql"
  export = "cart-payment-methods-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
