api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "minimum-order-value"
type = "function"
uid = "bc8dd245-096f-9fab-49fe-7df8f4f092c735732e98"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
