api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "order-value-discount"
type = "function"
uid = "c3a9a9ff-73c9-5e36-dfa0-eb3b2dba60e895ddf9f3"
description = "t:description"

  [[extensions.targeting]]
  target = "purchase.order-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
